"""add embed

Revision ID: 79a3203b20e8
Revises: 4e688a25e3a1
Create Date: 2024-08-08 11:26:46.987433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79a3203b20e8'
down_revision = '4e688a25e3a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtube_embed', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs_table', schema=None) as batch_op:
        batch_op.drop_column('youtube_embed')

    # ### end Alembic commands ###
