"""empty message

Revision ID: 85a70502b393
Revises: 79a3203b20e8
Create Date: 2024-08-08 12:03:48.812805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a70502b393'
down_revision = '79a3203b20e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['songs_table.id'], name=op.f('fk_favorites_table_song_id_songs_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites_table')
    # ### end Alembic commands ###
